### ISSUE TITLE
El Btn Añadir limpia los campos de texto al agregar una nueva nota

### ISSUE THREAD

**Issue by Jaime-Mora** [Leonardo-murataya/TodoList2024#12]
Pasos para producir el bug

1. Agregamos una nueva lista
2. Añadimos 2 notas
3. Creamos la lista
![Captura de pantalla 2024-04-16 111028](https://github.com/Leonardo-murataya/TodoList2024/assets/79118092/b80bca0d-80ad-462a-93a8-41adfad41bd6)

4. Editamos la lista
5. Cambiamos el texto de las  notas que ya se tenían 
![Captura de pantalla 2024-04-16 111140](https://github.com/Leonardo-murataya/TodoList2024/assets/79118092/4d008a81-f2ba-42f8-96de-c1697fee8ed8)

6. Añadimos más notas
cuando el usuario da clic en el **`boton` "Añadir"** el texto que se había cambiado se limpia para volver con los datos anteriores de la tarea 

https://github.com/Leonardo-murataya/TodoList2024/assets/79118092/edafe2d5-81c3-4da0-9280-ee7a538ae7e0

**Comment by Jaime-Mora** [comment]
El botón también limpia los campos de notas cuando se quiere crear una nueva lista

https://github.com/Leonardo-murataya/TodoList2024/assets/79118092/2dce0dea-7a87-4e49-8137-34502a75e7be

**Comment by Leonardo-murataya** [comment]
Solucionado
