### ISSUE TITLE
Botones Eliminar y Editar no funcionan

### ISSUE THREAD

**Issue by Jaime-Mora** [Leonardo-murataya/TodoList2024#15]
Estos botones no funcionan cuando el usuario crea una tarea con los siguientes caracteres:
**''' '''' ' ' '**

**Pasos para recrear el bug**

1. Ingresar al sistema https://todo-list-2024.netlify.app/
2. clic **Agregar Lista**
3. colocar los caracteres: '' '''' ' ' '** en todos los campos posibles
4. Clic **Crear**
![Captura de pantalla 2024-04-26 120227](https://github.com/Leonardo-murataya/TodoList2024/assets/79118092/b2821594-7d94-46f0-9b44-cc4f2795bda8)

5. Clic Bton de `editar` de la tarea creada 
6. Clic Bton de `eliminar` de la tarea creada

**Comment by Leonardo-murataya** [comment]
ya lo miro

**Comment by Leonardo-murataya** [comment]
ya quedo (me tomo 2 horas :D)
