### ISSUE TITLE
Manejar la aplicación en un solo idioma

### ISSUE THREAD

**Issue by Jaime-Mora** [Leonardo-murataya/TodoList2024#8]
Cambiar el título ToDo List

Amarillo = Traducir o usar otro texto como título
Azul celeste = Corregir Ortografia

![Captura de pantalla 2024-04-12 153057](https://github.com/Leonardo-murataya/TodoList2024/assets/79118092/0a24c2b6-6366-4a7c-8dc6-e5294e5930d4)

**Comment by Leonardo-murataya** [comment]
Corregido

![image](https://github.com/Leonardo-murataya/TodoList2024/assets/144365896/c1bcfca6-68bb-4360-9826-82b04729f38e)
